### ISSUE TITLE
Why aren't the services static?

### ISSUE THREAD

**Issue by AshotN** [ljlm0402/typescript-express-starter#24]
Is there any reason that classes like userService aren't static?

Wouldn't it be easier to call the method without having to initiate an object?

**Comment by ljlm0402** [comment]
@AshotN 


There is no particular reason. I think the way you speak is good. Thank you for your pull request.

**Comment by ragrag** [comment]
i think having non-static classes is much better out of the box for dependency injection of them and of other services/instances inside them without playing much around with IoC Containers

**Comment by AshotN** [comment]
Feel free to close this issue if you believe that there is no need to change anything.

**Comment by ljlm0402** [comment]
@ragrag 

Thank you very much for the comment.
If so, is that open source well organized? Sorry. I speak English with a translator incorrectly.

**Comment by ragrag** [comment]
@ljlm0402 
I would consider it very organized  however there are a couple of suggestions i would like to propose.

1. Having a separate file responsible for bootstrapping the database connection/initialization. (and associations in case of sequelize)
![image](https://user-images.githubusercontent.com/35541698/81853794-39a78b00-955d-11ea-8656-1a5c262f4ff5.png)

2. Having a flag or an option in the CLI to structure the project by entities/components instead of technical roles as shown in the image:
![image](https://user-images.githubusercontent.com/35541698/81854054-a15dd600-955d-11ea-91d5-2e7faeabfdb0.png)
Please see: https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md

**Comment by ljlm0402** [comment]
@ragrag 

Thanks for the good suggestions and detailed explanations.
It was very helpful. We will try to reflect it after review.
