### ISSUE TITLE
Is the template following the clean architecute from R.C. Martin?

### ISSUE THREAD

**Issue by Deel96** [ljlm0402/typescript-express-starter#77]
### Summary(요약)

Is the template following the clean architecture from R.C. Martin?

### Additional Details(추가적인 세부 사항)

the template project has a template like
/model ( or entities)
/service
/controller
/routes
pattern: https://github.com/ljlm0402/typescript-express-starter

But I have problems matching it to this architecture which many say is the de facto standard for a good software architecture

Like where do I find the entities, use cases, controllers etc.
For me only the controller layer is easy to find. In the template example project its also in the folder controllers.
In the example project the controllers use services and the services access the database.
If I try to map it to the pictures, use cases are the services and the entities are the models. But the models in the github project contain database specific code (for example typeorm notations).

![grafik](https://user-images.githubusercontent.com/37439779/111979299-31b56180-8b05-11eb-84af-73c91ef0ae7b.png)

**Comment by ljlm0402** [comment]
@Deel96 

First of all, please understand that we will speak in translation because we do not speak English.

Robert C Martin's clean architecture says that the common goal is to separate hierarchies and interests, albeit with minor differences, but adhere to the rules of dependency for such an architecture to work. Suppose you have to.

We have divided the folders specific to interests according to the definition and developed them by function.
Also, I was interested in developing it focusing on 3 Layer architecture.

![image](https://user-images.githubusercontent.com/42952358/112145617-ee024b00-8c1d-11eb-95f9-7330b4845192.png)


![image](https://user-images.githubusercontent.com/42952358/112145469-bf847000-8c1d-11eb-933d-40d3a5e20150.png)

> https://softwareontheroad.com/ideal-nodejs-project-structure/

If you don't get an answer to your question, I would appreciate it if you could say again what you think you know.  ˵ ͡ᵔ ͜ʟ ͡ᵔ ˵
